"""empty message

Revision ID: 08cf2a960a5e
Revises: 187414064689
Create Date: 2018-05-31 21:14:40.657096

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '08cf2a960a5e'
down_revision = '187414064689'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('company', 'location',
               existing_type=mysql.VARCHAR(length=24),
               nullable=True)
    op.alter_column('company', 'logo',
               existing_type=mysql.VARCHAR(length=256),
               nullable=True)
    op.alter_column('company', 'site',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('company', 'site',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
    op.alter_column('company', 'logo',
               existing_type=mysql.VARCHAR(length=256),
               nullable=False)
    op.alter_column('company', 'location',
               existing_type=mysql.VARCHAR(length=24),
               nullable=False)
    # ### end Alembic commands ###
